name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image (backend)
      run: docker build ./NovaBeatAI/backend --file ./NovaBeatAI/backend/Dockerfile --tag my-image-name:$(date +%s)
    - name: Build the Docker image (fastapi)
      run: docker build ./NovaBeatAI/fastapi --file ./NovaBeatAI/fastapi/Dockerfile --tag my-fastapi-image:$(date +%s)
